export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  USER_VIEW: "USER_VIEW",
  USER_SUSPEND: "USER_SUSPEND",
  USER_BAN: "USER_BAN",
  USER_SESSION_REVOKE: "USER_SESSION_REVOKE",
  AGENT_VIEW: "AGENT_VIEW",
  AGENT_CREATE: "AGENT_CREATE",
  AGENT_EDIT: "AGENT_EDIT",
  SPORT_VIEW: "SPORT_VIEW",
  EVENT_VIEW: "EVENT_VIEW",
  WALLET_VIEW: "WALLET_VIEW",
  TRANSACTION_VIEW: "TRANSACTION_VIEW",
  DEPOSIT_VIEW: "DEPOSIT_VIEW",
  DEPOSIT_APPROVE: "DEPOSIT_APPROVE",
  DEPOSIT_REJECT: "DEPOSIT_REJECT",
  WITHDRAWAL_VIEW: "WITHDRAWAL_VIEW",
  WITHDRAWAL_APPROVE: "WITHDRAWAL_APPROVE",
  WITHDRAWAL_REJECT: "WITHDRAWAL_REJECT",
  REFERRAL_VIEW: "REFERRAL_VIEW",
  REFERRAL_COMMISSION_VIEW: "REFERRAL_COMMISSION_VIEW",
  REFERRAL_CONFIG_VIEW: "REFERRAL_CONFIG_VIEW",
  REFERRAL_CONFIG_UPDATE: "REFERRAL_CONFIG_UPDATE",
  SESSION_VIEW: "SESSION_VIEW",
  AUDIT_VIEW: "AUDIT_VIEW",
  REPORT_VIEW: "REPORT_VIEW",
  PROVIDER_VIEW: "PROVIDER_VIEW",
  SETTINGS_VIEW: "SETTINGS_VIEW",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: readonly Permission[] = Object.values(PERMISSIONS);

export function permissionsForRole(role: "SUPER_ADMIN"): readonly Permission[] {
  if (role === "SUPER_ADMIN") return ALL_PERMISSIONS;
  return [];
}

export function can(granted: readonly string[], permission: Permission): boolean {
  return granted.includes(permission);
}
